/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/gyOuyndNW0I
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

"use client"

import { useState } from "react"
import Link from "next/link"
// import {CheckCir} from '@radix-ui/react-icons'
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuItem } from "@/components/ui/dropdown-menu"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function Track() {
  const [currentStep, setCurrentStep] = useState(1)
  return (
    <div className="bg-[#fff] flex min-h-[100dvh] flex-col">
      <header className="flex h-16 items-center justify-between px-4">
        <Link href="#" prefetch={false}>
          <UsbIcon className="h-6 w-6" />
        </Link>
        <div className="flex items-center gap-4">
          <Link href="#" prefetch={false}>
            <SearchIcon className="h-6 w-6" />
          </Link>
          <DropdownMenu>
            <DropdownMenuTrigger>
              <MenuIcon className="h-6 w-6" />
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end">
              <DropdownMenuItem>
                <Link href="#" prefetch={false}>
                  About
                </Link>
              </DropdownMenuItem>
              <DropdownMenuItem>
                <Link href="#" prefetch={false}>
                  Contact
                </Link>
              </DropdownMenuItem>
              <DropdownMenuItem>
                <Link href="#" prefetch={false}>
                  FAQ
                </Link>
              </DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
        </div>
      </header>
      <main className="flex-1">
        <section className="bg-muted py-8 px-4">
          <h1 className="text-2xl font-bold">USPS Tracking</h1>
          <p className="text-muted-foreground">Enter your tracking number to check the status of your package.</p>
        </section>
        <section className="px-4 py-8">
          <div>
            {currentStep === 1 && (
              <div>
                <h2 className="text-lg font-bold">Address Details</h2>
                <form className="space-y-4">
                  <div className="space-y-2">
                    <Label htmlFor="name">Name</Label>
                    <Input id="name" placeholder="Enter your name" />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="address">Address</Label>
                    <Input id="address" placeholder="Enter your address" />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="city">City</Label>
                    <Input id="city" placeholder="Enter your city" />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="state">State</Label>
                    <Input id="state" placeholder="Enter your state" />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="zip">ZIP Code</Label>
                    <Input id="zip" placeholder="Enter your ZIP code" />
                  </div>
                  <Button onClick={() => setCurrentStep(2)}>Next</Button>
                </form>
              </div>
            )}
            {currentStep === 2 && (
              <div>
                <h2 className="text-lg font-bold">Payment Information</h2>
                <form className="space-y-4">
                  <div className="space-y-2">
                    <Label htmlFor="card-number">Card Number</Label>
                    <Input id="card-number" placeholder="Enter your card number" />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="name-on-card">Name on Card</Label>
                    <Input id="name-on-card" placeholder="Enter the name on your card" />
                  </div>
                  <div className="grid grid-cols-3 gap-4">
                    <div className="space-y-2">
                      <Label htmlFor="expiration-date">Expiration Date</Label>
                      <Input id="expiration-date" placeholder="MM/YY" />
                    </div>
                    <div className="space-y-2">
                      <Label htmlFor="cvv">CVV</Label>
                      <Input id="cvv" placeholder="CVV" />
                    </div>
                  </div>
                  <Button onClick={() => setCurrentStep(3)}>Next</Button>
                </form>
              </div>
            )}
            {currentStep === 3 && (
              <div>
                <div className="flex flex-col items-center justify-center gap-4 py-12">
                  <svg width="15" height="15" viewBox="0 0 15 15" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M7.49991 0.877045C3.84222 0.877045 0.877075 3.84219 0.877075 7.49988C0.877075 11.1575 3.84222 14.1227 7.49991 14.1227C11.1576 14.1227 14.1227 11.1575 14.1227 7.49988C14.1227 3.84219 11.1576 0.877045 7.49991 0.877045ZM1.82708 7.49988C1.82708 4.36686 4.36689 1.82704 7.49991 1.82704C10.6329 1.82704 13.1727 4.36686 13.1727 7.49988C13.1727 10.6329 10.6329 13.1727 7.49991 13.1727C4.36689 13.1727 1.82708 10.6329 1.82708 7.49988ZM10.1589 5.53774C10.3178 5.31191 10.2636 5.00001 10.0378 4.84109C9.81194 4.68217 9.50004 4.73642 9.34112 4.96225L6.51977 8.97154L5.35681 7.78706C5.16334 7.59002 4.84677 7.58711 4.64973 7.78058C4.45268 7.97404 4.44978 8.29061 4.64325 8.48765L6.22658 10.1003C6.33054 10.2062 6.47617 10.2604 6.62407 10.2483C6.77197 10.2363 6.90686 10.1591 6.99226 10.0377L10.1589 5.53774Z" fill="currentColor" fill-rule="evenodd" clip-rule="evenodd"></path></svg>
                  <h2 className="text-lg font-bold">Payment Successful</h2>
                  <p className="text-muted-foreground">Your payment has been processed successfully.</p>
                </div>
              </div>
            )}
          </div>
        </section>
      </main>
      <footer className="bg-muted py-8 px-4">
        <div className="container mx-auto grid grid-cols-2 md:grid-cols-4 gap-y-8">
          <div className="space-y-2">
            <h3 className="text-lg font-bold">Helpful Links</h3>
            <ul className="space-y-1">
              <li>
                <Link href="#" className="text-muted-foreground hover:underline" prefetch={false}>
                  FAQ
                </Link>
              </li>
              <li>
                <Link href="#" className="text-muted-foreground hover:underline" prefetch={false}>
                  Contact Us
                </Link>
              </li>
              <li>
                <Link href="#" className="text-muted-foreground hover:underline" prefetch={false}>
                  Shipping Information
                </Link>
              </li>
              <li>
                <Link href="#" className="text-muted-foreground hover:underline" prefetch={false}>
                  Returns and Refunds
                </Link>
              </li>
            </ul>
          </div>

          <div className="space-y-2">
            <h3 className="text-lg font-bold">Contact</h3>
            <ul className="space-y-1">
              <li>
                <Link href="#" className="text-muted-foreground hover:underline" prefetch={false}>
                  Contact Us
                </Link>
              </li>
              <li>
                <Link href="#" className="text-muted-foreground hover:underline" prefetch={false}>
                  FAQ
                </Link>
              </li>
              <li>
                <Link href="#" className="text-muted-foreground hover:underline" prefetch={false}>
                  Shipping Information
                </Link>
              </li>
              <li>
                <Link href="#" className="text-muted-foreground hover:underline" prefetch={false}>
                  Returns and Refunds
                </Link>
              </li>
            </ul>
          </div>
          <div className="space-y-2">
            <h3 className="text-lg font-bold">Legal</h3>
            <ul className="space-y-1">
              <li>
                <Link href="#" className="text-muted-foreground hover:underline" prefetch={false}>
                  Terms of Service
                </Link>
              </li>
              <li>
                <Link href="#" className="text-muted-foreground hover:underline" prefetch={false}>
                  Privacy Policy
                </Link>
              </li>
              <li>
                <Link href="#" className="text-muted-foreground hover:underline" prefetch={false}>
                  Cookie Policy
                </Link>
              </li>
            </ul>
          </div>
        </div>
        <div className="text-muted-foreground mt-4 text-center">&copy; 2024 USPS. All rights reserved.</div>
      </footer>
    </div>
  )
}

function MenuIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  )
}


function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}


function UsbIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="10" cy="7" r="1" />
      <circle cx="4" cy="20" r="1" />
      <path d="M4.7 19.3 19 5" />
      <path d="m21 3-3 1 2 2Z" />
      <path d="M9.26 7.68 5 12l2 5" />
      <path d="m10 14 5 2 3.5-3.5" />
      <path d="m18 12 1-1 1 1-1 1Z" />
    </svg>
  )
}
